spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam

  profiles:
    include:
      - db

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
