spring:
  jpa:
    hibernate:
      #ddl-auto: validate
      ddl-auto: none
  datasource:
    hikari:
      schema: accessmanagement
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    locations: classpath:db/migration/
    lock-retry-count: 300

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
