fint:
  kafka:
    topic:
      org-id: ${fint.org-id}
      domain-context: kontroll
    application-id: ${fint.application-id}

spring:
  kafka:
    security:
      protocol: 'SSL'
    consumer:
      group-id: ${fint.application-id}

