fint:
  org-id: fintlabs.no
  application-id: fint-kontroll-access-management-catalog
  cache:
      defaultCacheEntryTimeToLiveMillis: 518400000
      defaultCacheHeapSize: 1000000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam

  profiles:
    include:
      - db
      - kafka

server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    root: INFO
    org.apache.kafka: INFO

opa:
  jsonexport:
    filename: opaexport.json
