fint:
  kafka:
    topic:
      org-id: ${fint.org-id}
      domain-context: kontroll
    application-id: ${fint.application-id}

spring:
  kafka:
    consumer:
      group-id: ${fint.application-id}
      security:
        protocol: SSL
    producer:
      security:
        protocol: SSL
