apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: afk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-access-mngmnt-catalog
  app.kubernetes.io/instance: fint-kontroll-access-mngmnt-catalog_afk-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: afk.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "afk.no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "afk-no.kontroll.*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "afk-no.kontroll.*"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/afk-no/api/accessmanagement/v1"
      - op: replace
        path: "/spec/url/basePath"
        value: "/afk-no"
      - op: replace
        path: "/spec/env/2/value"
        value: "afk.no"
    target:
      kind: Application
      name: fint-kontroll-access-mngmnt-catalog

  - patch: |-
      - op: replace
        path: "/spec/itemPath"
        value: "vaults/aks-api-vault/items/kontroll-access-management-catalog-afk-no"
    target:
      kind: OnePasswordItem
      name: fint-kontroll-access-mngmnt-secrets

