ALTER TABLE accessassignment ADD COLUMN id bigint generated by default as identity;
ALTER TABLE accessassignment DROP CONSTRAINT accessassignment_pkey;
ALTER TABLE accessassignment DROP CONSTRAINT scope_fk;
ALTER TABLE accessassignment ADD PRIMARY KEY (id);
ALTER TABLE accessassignment DROP COLUMN scope_id;

create table assignment_scope
(
    scope_id bigint,
    assignment_id bigint,
    primary key (scope_id, assignment_id),
    foreign key (scope_id) references scope (id),
    foreign key (assignment_id) references accessassignment (id)
);
