create table accessrole
(
    id             int8 generated by default as identity,
    access_role_id varchar(255),
    name           varchar(255),
    primary key (access_role_id)
);

create table accessuser
(
    id          bigint generated by default as identity,
    resource_id varchar(255),
    user_id     varchar(255),
    user_name   varchar(255),
    first_name  varchar(255),
    last_name   varchar(255),
    primary key (resource_id)
);
