create table accesspermission
(
    id            bigint generated by default as identity,
    access_role_id varchar(255),
    feature_id    bigint,
    operation     varchar(255),
    primary key (id)
);
