create table scope
(
    id         bigint generated by default as identity,
    objecttype varchar(255),
    primary key (id)
);

create table org_unit
(
    id          bigint generated by default as identity,
    org_unit_id varchar(255),
    primary key (org_unit_id)
);

create table scope_orgunit
(
    scope_id    bigint,
    org_unit_id varchar(255),
    primary key (scope_id, org_unit_id),
    foreign key (scope_id) references scope (id),
    foreign key (org_unit_id) references org_unit (org_unit_id)
);
