apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kontroll-access-mngmnt-catalog
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: fint-kontroll-access-mngmnt-catalog
    app.kubernetes.io/instance: fint-kontroll-access-mngmnt-catalog_fintlabs-no

spec:
  #  port: 8080
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kontroll-access-management-catalog:latest
  imagePullPolicy: Always

#  onePassword:
#    item-path: 'test'

  url:
    hostname: 'kontroll.vigoiks.no'
    basePath: '/beta/fintlabs-no'

  ingress:
    enabled: true
    basePath: '/beta/fintlabs-no/api/accessmanagement/v1'
    middlewares:
      - fint-kontroll-sso

  env:
    - name: TZ
      value: Europe/Oslo
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx2G'
    - name: fint.kontroll.authorization.authorized-org-id
      value: 'vigo.no'

  kafka:
    enabled: true
    acls:
      - topic: 'fintlabs-no.kontroll.*'
        permission: read
      - topic: 'fintlabs-no.kontroll.*'
        permission: admin

  database:
    database: fint-kontroll

  envFrom:
    - configMapRef:
        name: fint-environment
    - configMapRef:
        name: fint-kontroll-access-mngmnt-config
